### ISSUE TITLE
FR: Cache link resolving results

### ISSUE THREAD

**Issue by jrfnl** [technote-space/broken-link-checker-action#131]
## Please describe your suggestion: 

By the looks of it, this action:
* Scans for links in a webpage
* Tries to resolve those links
* Moves on to the next page
* Tries to resolve the links on that page
* etc

For a website (in this case a GH Pages website) with an extensive menu in the page header and more links in the page footer, where the page header and page footer of all pages are the same, this results in the links found in the page header and the page footer being resolved hundreds of times, making the broken link scan really slow and also hitting websites with a lot of duplicate requests.

## Describe the solution you'd like: 
I'd like to suggest implementing some form of cache memory which during a run of the action, keeps track of all links encountered and what the result was of resolving that link.

For each link encountered, the action would then first check the cache if the link was already resolved before, if so: skip checking the link again. If not: check the link and write the result to the cache.

I suspect that for a lot of sites, that would make the scan much, much faster, while still being just as accurate.

## Describe alternatives you've considered: 
None.

## Additional context: 

This is basically the same issue as #100, previously opened by @jasikpark and closed without reply.

**Comment by jasikpark** [comment]
@jrfnl i ended up just running `blc` manually via a node github action
