### ISSUE TITLE
DNS Failures Don't Report Broken?

### ISSUE THREAD

**Issue by kingthorin** [technote-space/broken-link-checker-action#135]
## Describe the bug: バグの概要
I seems the action doesn't report links that fail DNS as broken?

## To Reproduce: 再現手順
Setup the action, run it on a target that has links that fail DNS resolution.

## Expected behavior: 期待する動作
Links that fail DNS resolution should be treated as 404.

## Screenshots: スクリーンショット
N/A

## Operating environment: バグが発生した環境
 - Version of software: technote-space/broken-link-checker-action@v2
 - OS: [e.g. Windows10]: ubuntu-latest
 - Browser: [e.g. Chrome, Safari] - N/A
 - etc.

**Comment by shilpiprd** [comment]
What are some of the corresonding links / files? Any links?

**Comment by kingthorin** [comment]
For testing, just host/create a dummy page with a link to `<a href="https://shouldfailtolookup.com/">will fail</a>`.

**Comment by kingthorin** [comment]
I threw it up on a GH Page to make it easier for you: https://kingthorin.github.io/test/

**Comment by kingthorin** [comment]
Any plans to address this?

**Comment by kingthorin** [comment]
Has this actually been fixed?
