### ISSUE TITLE
Single issue per run

### ISSUE THREAD

**Issue by kingthorin** [technote-space/broken-link-checker-action#80]
## Please describe your suggestion: 提案の概要
If would be really nice if there was an option to include all the results in a single ticket, instead of creating a new ticket for each broken link.

## Describe the solution you'd like: 考えうる解決方法
See above.

## Describe alternatives you've considered: 考えうる代替案
Looking for another GitHub action.

## Additional context: 補足
N/A

**Comment by technote-space** [comment]
This GitHub action links the issue with the URL.
Therefore your proposal cannot be implemented.
Please use another action.
Thank you.
